module.exports = [
    { name: ['ميليوداس', 'meliodas'], image: 'https://cdn.myanimelist.net/images/characters/11/269177.jpg' },
    { name: ['إليزابيث', 'elizabeth'], image: 'https://cdn.myanimelist.net/images/characters/8/269181.jpg' },
    { name: ['بان', 'ban'], image: 'https://cdn.myanimelist.net/images/characters/16/269183.jpg' },
    { name: ['إسكانور', 'escanor'], image: 'https://cdn.myanimelist.net/images/characters/8/345228.jpg' },
    { name: ['ليفاي', 'levi'], image: 'https://cdn.myanimelist.net/images/characters/2/241417.jpg' },
    { name: ['ايرين', 'eren'], image: 'https://cdn.myanimelist.net/images/characters/10/216823.jpg' },
    { name: ['ميكاسا', 'mikasa'], image: 'https://cdn.myanimelist.net/images/characters/9/215563.jpg' },
    { name: ['لوفي', 'luffy'], image: 'https://cdn.myanimelist.net/images/characters/9/310307.jpg' },
    { name: ['زورو', 'zoro'], image: 'https://cdn.myanimelist.net/images/characters/3/100534.jpg' },
    { name: ['سانجي', 'sanji'], image: 'https://cdn.myanimelist.net/images/characters/5/136769.jpg' },
    { name: ['أستا', 'asta'], image: 'https://cdn.myanimelist.net/images/characters/2/323366.jpg' },
    { name: ['يونو', 'yuno'], image: 'https://cdn.myanimelist.net/images/characters/6/340058.jpg' },
    { name: ['تانجيرو', 'tanjiro'], image: 'https://cdn.myanimelist.net/images/characters/8/384239.jpg' },
    { name: ['نيزوكو', 'nezuko'], image: 'https://cdn.myanimelist.net/images/characters/4/384240.jpg' },
    { name: ['ايتشيغو', 'ichigo'], image: 'https://cdn.myanimelist.net/images/characters/3/305260.jpg' },
    { name: ['آيزن', 'aizen'], image: 'https://cdn.myanimelist.net/images/characters/15/82766.jpg' },
    { name: ['غون', 'gon'], image: 'https://cdn.myanimelist.net/images/characters/11/242277.jpg' },
    { name: ['كيلوا', 'killua'], image: 'https://cdn.myanimelist.net/images/characters/2/327920.jpg' },
    { name: ['سونغ جينو', 'jinwoo'], image: 'https://cdn.myanimelist.net/images/characters/8/533202.jpg' },
    { name: ['ثورفين', 'thorfinn'], image: 'https://cdn.myanimelist.net/images/characters/8/386047.jpg' },
    { name: ['غوجو', 'gojo'], image: 'https://cdn.myanimelist.net/images/characters/15/422168.jpg' },
    { name: ['سوكونا', 'sukuna'], image: 'https://cdn.myanimelist.net/images/characters/8/422170.jpg' },
    { name: ['ناروتو', 'naruto'], image: 'https://cdn.myanimelist.net/images/characters/9/131317.jpg' },
    { name: ['ساسكي', 'sasuke'], image: 'https://cdn.myanimelist.net/images/characters/9/108633.jpg' },
    { name: ['غوكو', 'goku'], image: 'https://cdn.myanimelist.net/images/characters/3/308102.jpg' },
    { name: ['فيجيتا', 'vegeta'], image: 'https://cdn.myanimelist.net/images/characters/13/328212.jpg' }
];
